FROM knovault_base:latest

WORKDIR /app

# Copy the Go module files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the application code
COPY . .

# Install NPM dependencies
RUN npm install

# Build the application
RUN make build

# Expose the application port
EXPOSE 1323

# Set the entry point for production
CMD ["./bin/knovault"]