FROM golang:1.23-bullseye

# Set environment variables
ENV NODE_VERSION=18.x

# Install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    git \
    make \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Install Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION} | bash - \
    && apt-get install -y nodejs

# Install Templ
RUN go install github.com/a-h/templ/cmd/templ@latest