// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package CardCreator

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CardCreatorInterface() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = CardCreatorInterfaceJavascript().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container mx-auto\"><h1 class=\"text-3xl font-bold mb-6\">Extended Card Creator</h1><div class=\"flex gap-8\"><div class=\"w-1/2\"><h2 class=\"text-xl font-semibold mb-4\">Settings</h2><form id=\"cardForm\" class=\"space-y-6\"><!-- Card Dimensions --><div><h3 class=\"text-lg font-semibold mb-2\">Card Dimensions</h3><div><label for=\"cardWidth\" class=\"block\">Width: <span id=\"widthValue\">300</span>px</label> <input type=\"range\" id=\"cardWidth\" name=\"cardWidth\" min=\"200\" max=\"800\" value=\"300\" class=\"w-full\"></div><div><label for=\"cardHeight\" class=\"block\">Height: <span id=\"heightValue\">400</span>px</label> <input type=\"range\" id=\"cardHeight\" name=\"cardHeight\" min=\"200\" max=\"800\" value=\"400\" class=\"w-full\"></div></div><!-- Edge Content --><div><h3 class=\"text-lg font-semibold mb-2\">Edge Content</h3><div class=\"space-y-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, edge := range []string{"top", "bottom", "left", "right"} {
			templ_7745c5c3_Err = EdgeContent(edge).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><!-- Middle Content --><div><h3 class=\"text-lg font-semibold mb-2\">Middle Content</h3><div id=\"middleContents\" class=\"space-y-4\"><!-- Middle content sections will be added here dynamically --></div><button type=\"button\" id=\"addMiddleContent\" class=\"mt-2 bg-blue-500 text-white px-4 py-2 rounded\">Add Middle Content</button></div><!-- Card Border --><div><h3 class=\"text-lg font-semibold mb-2\">Card Border</h3>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = BorderControls("card").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ShadowControls("card").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></form></div><div class=\"w-1/2\"><h2 class=\"text-xl font-semibold mb-4\">Preview</h2><div id=\"cardPreview\" class=\"border border-gray-300 p-4 min-h-[400px]\"></div><h2 class=\"text-xl font-semibold mt-8 mb-4\">Generated HTML</h2><pre id=\"generatedHTML\" class=\"bg-gray-800 text-white p-4 rounded overflow-x-auto\"></pre><button id=\"copyHTML\" class=\"mt-4 bg-green-500 text-white px-4 py-2 rounded\">Copy HTML</button></div></div></div><template id=\"middleContentTemplate\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = MiddleContent().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</template>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
