// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package CardCreator

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func MiddleContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"middle-content-section bg-white p-4 rounded shadow\"><div class=\"flex items-center justify-between mb-2\"><select name=\"middleContentType[]\" class=\"p-2 border rounded\"><option value=\"text\">Text</option> <option value=\"image\">Image</option> <option value=\"list\">List</option> <option value=\"table\">Table</option></select> <button type=\"button\" class=\"remove-middle-content bg-red-500 text-white px-2 py-1 rounded\">Remove</button></div><div class=\"content-controls\"><!-- Controls will be dynamically added based on the selected type --></div><div class=\"mt-2\"><label class=\"block\">Height: <span class=\"height-value\">25</span>%</label> <input type=\"range\" name=\"middleContentHeight[]\" min=\"1\" max=\"100\" value=\"25\" class=\"w-full\"></div><div class=\"mt-2\"><label class=\"block\">Background Color:</label> <input type=\"color\" name=\"middleContentBgColor[]\" value=\"#ffffff\"></div><div class=\"mt-2\"><h4 class=\"font-semibold\">Border:</h4>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = BorderControls("middleContent[]").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ShadowControls("middleContent[]").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
